name: Build Image
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Input version (SemVer) tag of tagref to genarte images for'
        required: false

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  VERSION_REGEX: ^(refs\/tags\/)?v([0-9]+.[0-9]+.[0-9]+.*)$
  # DOCKER_IMAGE - overrides the docker image name (name is repo name with docker- prefix stripped)

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set.outputs.image }}
      kubeVer: ${{ steps.post.outputs.kubeVer }}
      kubeTag: v${{ steps.post.outputs.kubeVer }}
      kubeMinor: ${{ steps.kubever.outputs.minor }}

    steps:
      -
        uses: actions/github-script@v4
        id: set
        with:
          script: |
            const repo = '${{ github.event.repository.name }}'.toLowerCase().replace(/^docker-/, '')
            const versionRegex = new RegExp('${{ env.VERSION_REGEX }}')
            // docker image
            core.setOutput('image', '${{ env.DOCKER_IMAGE }}' ?
              '${{ env.DOCKER_IMAGE }}' :
              `${{ github.event.organization.login }}/${ repo }`
            )
            // push is set to true when pushes are enabled
            core.setOutput('push', versionRegex.test('${{ github.event.inputs.version }}'))
      -
        name: Kubectl Version
        id: kubever
        if: steps.set.outputs.push == 'true'
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: '${{ github.event.inputs.version }}'
          version_extractor_regex: '${{ env.VERSION_REGEX }}'
      -
        uses: actions/github-script@v4
        id: post
        if: steps.set.outputs.push == 'true'
        with:
          script: |
            core.setOutput('kubeVer', '${{ steps.kubever.outputs.major }}.${{ steps.kubever.outputs.minor }}.${{ steps.kubever.outputs.patch }}')
