---
name: Get updated releases
on:
  # repository_dispatch:
  #   types: [effectively-disabled]
  schedule:
    - cron: '0 */24 * * *'

jobs:
  updated:
    name: Get updated
    uses: ./.github/workflows/upstream.updated-releases.yaml
    secrets: inherit
    with:
      versions: |-
        [
          "^v1\.26\.[0-9]+$",
          "^v1\.27\.[0-9]+$",
          "^v1\.28\.[0-9]+$",
          "^v1\.29\.[0-9]+$",
          "^v1\.30\.[0-9]+$"
        ]
